package org.capstone.job_fair.models.enums;

public enum NotificationAction {
    ASSIGNMENT, APPLICATION, UN_ASSIGNMENT, WARNING_TASK_MANAGER, WARNING_TASK_SUPERVISOR_PROFILE, WARNING_TASK_SUPERVISOR_ASSIGN, WARNING_TASK_DECORATOR, WARNING_INTERVIEW
}
