package org.capstone.job_fair.models.enums;

public enum NotificationType {
    NOTI, VISIT_JOB_FAIR, VISIT_JOB_FAIR_BOOTH, WAITING_ROOM, INTERVIEW_ROOM, KICK_USER, NEW_REFUND_REQUEST, APPROVE_REFUND_REQUEST, REJECT_REFUND_REQUEST
}
