name: CI

on:
  push:
    branches: [ main ]


jobs:
   #Build's job
  build:
    name: Build
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v1
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      #Set up Maven cache
      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      #Build the application using Maven
      - name: Build with Maven
        run: mvn clean install
      #Build the application using Maven
      - name: Upload JAR
        #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
        uses: actions/upload-artifact@v2
        with:
          #Set artifact name
          name: artifact
          #From this path
          path: target/jobfair-backend.jar
          
  #Test's job
  test:
    env:
    ## Sets environment variable
      DATASOURCE_PASSWORD: ${{secrets.DATASOURCE_PASSWORD}}
      DATASOURCE_URL: ${{secrets.DATASOURCE_URL}}
      DATASOURCE_PORT: ${{secrets.DATASOURCE_PORT}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATASOURCE_USERNAME: ${{secrets.DATASOURCE_USERNAME}}
      JWT_EXPIRATION: ${{secrets.JWT_EXPIRATION}}
      JWT_REFESH_EXPIRATION: ${{secrets.JWT_REFESH_EXPIRATION}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      SPRING_MAIL_HOST: ${{secrets.SPRING_MAIL_HOST}}
      SPRING_MAIL_PORT: ${{secret.SPRING_MAIL_PORT}}
      SPRING_MAIL_SNMP_PORT: ${{secrets.SPRING_MAIL_SNMP_PORT}}
      SPRING_MAIL_PROPERTIES_MAIL_TRANSPORT_PROTOCOL: ${{secret.SPRING_MAIL_PROPERTIES_MAIL_TRANSPORT_PROTOCOL}}
      SPRING_MAIL_USERNAME: ${{secrets.SPRING_MAIL_USERNAME}}
      SPRING_MAIL_PASSWORD: ${{secrets.SPRING_MAIL_PASSWORD}}
      MAIL_FROM: ${{secrets.MAIL_FROM}}
      SPRING_MAIL_SMTP_AUTH: ${{secrets.SPRING_MAIL_SMTP_AUTH}}
      SPRING_MAIL_SMTP_STARTTLS: ${{secrets.SPRING_MAIL_SMTP_STARTTLS}}
      SPRING_MAIL_SMTP_STARTTLS_REQIRED: ${{secrets.SPRING_MAIL_SMTP_STARTTLS_REQIRED}}
      API_DOMAIN: ${{secret.API_DOMAIN}}
      API_PORT: ${{secrets.API_PORT}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    #Depends on build's job
    needs: build
    name: Test
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        #Download the artifact which was uploaded in the build's job
        uses: actions/download-artifact@v2
        with:
          name: artifact
    #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
   #Run file
      - name: Run file
        run: nohup java -jar jobfair-backend.jar &
